const SERVICE_RULES = {
  Academics: {
    subCategories: ['Home Tuitions', 'Tuition Center', 'School', 'College'],
    keywords: [
      'Maths',
      'Science',
      'Language',
      'English',
      'Hindi',
      'Sanskrit',
      'Spanish',
      'French',
      'German',
      'Mandarin',
      'Italian',
      'Accounts',
      'Economics',
      'Physics',
      'Chemistry',
    ],
  },
  Music: {
    subCategories: ['Home Classes', 'Academy'],
    keywords: [
      'Home Classes',
      'Guitar',
      'Academy',
      'Piano',
      'Drums',
      'Violin',
      'Flute',
      'Vocals',
      'Singing',
      'Saxophone',
    ],
  },
  Dance: {
    subCategories: ['Home Classes', 'Academy'],
    keywords: ['Zumba', 'Bhangra', 'Salsa', 'Jiving', 'Freestyle', 'Breakdance'],
  },
  'Fitness & Sports': {
    subCategories: ['Home Classes', 'Academy'],
    keywords: [
      'Yoga',
      'Pilates',
      'Fitness',
      'Zumba',
      'Skateboarding',
      'Skating',
      'Cricket',
      'Football',
      'Pickle Ball',
      'Badminston',
      'Tennis',
      'Table Tennis',
      'Chess',
      'Padel',
      'Gym',
      'Strength Training',
      'Core',
      'Strength',
      'Weight Training',
      'Weights',
      'Sudoku',
      'Puzzle',
    ],
  },
  'Home Cooking': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Food',
      'Cook',
      'Italian',
      'Indian',
      'Mexican',
      'Rajasthani',
      'Gujrati',
      'Bengali',
      'Chinese',
      'Burgers',
      'Pizza',
      'Asian',
      'Sushi',
      'Dimsums',
      'Sushi Cake',
      'Salads',
      'Ramen',
      'Pasta',
      'Biryani',
    ],
  },
  'Home Catering': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Food',
      'Cook',
      'Italian',
      'Indian',
      'Mexican',
      'Rajasthani',
      'Gujrati',
      'Bengali',
      'Chinese',
      'Burgers',
      'Pizza',
      'Asian',
      'Sushi',
      'Dimsums',
      'Sushi Cake',
      'Salads',
      'Ramen',
      'Pasta',
      'Biryani',
    ],
  },
  'Home Baker': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Cakes',
      'Pastry',
      'Brownie',
      'Muffins',
      'Tarts',
      'Eggless',
      'Quiche',
      'Fondant',
      'Chocolate',
      'Protein Bar',
      'Granola',
      'Bread',
    ],
  },
  Catering: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Food',
      'Cook',
      'Italian',
      'Indian',
      'Mexican',
      'Rajasthani',
      'Gujrati',
      'Bengali',
      'Chinese',
      'Burgers',
      'Pizza',
      'Asian',
      'Sushi',
      'Dimsums',
      'Sushi Cake',
      'Salads',
      'Ramen',
      'Pasta',
      'Biryani',
    ],
  },
  'Professional Baker': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: ['Cakes', 'Pastry', 'Brownie', 'Muffins', 'Tarts', 'Eggless', 'Quiche', 'Fondant'],
  },
  Workshops: {
    subCategories: ['Home Workshops', 'Online Workshops'],
    keywords: ['Summer', 'Winter', 'Story Telling', 'Book Reading', 'Cooking', 'Baking', 'Workshop'],
  },
  Photography: {
    subCategories: ['Academy'],
    keywords: ['Lens', 'Camera', 'Video', 'Wedding', 'Birthday'],
  },
  Technology: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'AI',
      'Python',
      'Automation',
      'Coding',
      'Image Creation',
      'Digital Marketing',
      'Designing',
      'Scratch',
      'Prompt',
      'Chat GPT',
      'LLM',
      'Java',
      'Clone',
      'Video Generaion',
    ],
  },
  Consulting: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Financial Planning',
      'Tax Consultancy',
      'CA',
      'Chartered Accountant',
      'Returns',
      'Landscaping',
      'Garden',
      'Flowers',
    ],
  },
  Finance: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Financial Planning',
      'Tax Planning',
      'Accounting',
      'Investments',
      'Mutual Finds',
      'Stocks',
      'Broker',
      'Money',
      'Bonds',
      'Crypto',
    ],
  },
  Groceries: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Kitchen',
      'Grocery',
      'Vegetables',
      'Fruits',
      'Sauce',
      'Milk',
      'Bread',
    ],
  },
  'Home Products': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Candles',
      'Handicrafts',
      'Bathroom Products',
      'Artefacts',
      'Sculptures',
      'Show Piece',
      'Garden',
      'Furniture',
      'Flooring',
      'Marble',
      'Wooden',
      'Carpenter',
      'Electrical',
      'Plumbing',
      'Solar',
      'Gate',
      'Light',
      'Paint',
      'Wall',
    ],
  },
  'Apparels & Footwear': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Fashion',
      'Shoes',
      'Chappals',
      'Sandals',
      'Suits',
      'Shirts',
      'Kurti',
      'Indo western',
      'Coord Sets',
    ],
  },
  Law: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Tax',
      'Civil',
      'Criminal',
      'Corporate',
      'Arbitration',
      'High Court',
      'Court',
      'Supreme Court',
      'District Court',
      'Judge',
      'Lawyer',
      'Advocate',
      'Bail',
    ],
  },
  Medical: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: ['Doctor', 'Nurse', 'Medical Equipment'],
  },
  'Art & Craft': {
    subCategories: ['Home Classes', 'Academy'],
    keywords: ['Origami', 'Painting', 'Drawing', 'Colouring'],
  },
  'Home Interiors': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: ['Interiros', 'Designing'],
  },
  Construction: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: ['House', 'Farm House', 'Flat', 'Floor', 'Marble', 'Stone', 'Wall'],
  },
  'Real Estate': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: ['Real Estate Consultant', 'Property', 'Buy', 'Sell'],
  },
  'Event Planner': {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [
      'Birthday',
      'Decor',
      'Wedding',
      'Anniversary',
      'Balloon',
      'Props',
      'Corporate Event',
      'Rides',
    ],
  },
  Gifting: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: ['Corporate', 'Gift Set'],
  },
  Other: {
    subCategories: ['Basic Services', 'Premium Services', 'Specialized Services'],
    keywords: [],
  },
};

export default SERVICE_RULES;


